### ISSUE TITLE
When the PI branch launches, I want a reference to it on the social intranet section

### ISSUE THREAD

**Issue by pilz** [syslabcom/syslabcom.theme2012#3]
The new social intranet section currently says "Social Intranet Solutions". Once Guido unveils the brand, I want to make clear that we do Social Intranets based on that brand. Can we do that visually? Should we do it textually? Do we need to arrange for space on that page?

**Comment by cornae** [comment]
What is the brand name now finally then? Is there a logo? It depends a bit…

**Comment by pilz** [comment]
Brand name is Quaive. Logo AI file sent to you my email
