### ISSUE TITLE
showcase page titles collide with language switch

### ISSUE THREAD

**Issue by pilz** [syslabcom/syslabcom.theme2012#6]
![bildschirmfoto 2015-10-07 um 22 08 55](https://cloud.githubusercontent.com/assets/138906/10349715/13357b70-6d40-11e5-8b76-41326adb8b5c.png)

**Comment by cornae** [comment]
Works for me…

![image](https://cloud.githubusercontent.com/assets/738601/10368052/c9b4edb6-6dd3-11e5-8b2d-bd7110c9999d.png)

![image](https://cloud.githubusercontent.com/assets/738601/10368025/a4b8675e-6dd3-11e5-9dd5-449479a98eae.png)

**Comment by cornae** [comment]
Ahh. When you directly go to a page of a show case it happens…

**Comment by cornae** [comment]
Fixed
