### ISSUE TITLE
Call to action - book demo

### ISSUE THREAD

**Issue by pilz** [syslabcom/syslabcom.theme2012#9]
I added two pages to the intranet-solution section to book a demo. I stole the "book a demo" image from quaive.com and added it there. Also I included a mailto link to book a demo. The former needs something that fits in and the latter should invite to click, I guess. Can you wield your wand?
https://github.com/syslabcom/syslabcom.theme2012/commit/f58ff7629ef028d73022f0260881018a4b1619ec

**Comment by cornae** [comment]
When?

**Comment by pilz** [comment]
After Slidebank

**Comment by cornae** [comment]
Now no space? :)

**Comment by pilz** [comment]
If you can? :)

Alexander Pilz (mobil)

**Comment by cornae** [comment]
In the word Slide bank :)

> Op 23 okt. 2015, om 20:48 heeft Alexander Pilz notifications@github.com het volgende geschreven:
> 
> If you can? :)
> 
> Alexander Pilz (mobil)
>

**Comment by pilz** [comment]
Argh, keep it in, me just too ignorant

Alexander Pilz (mobil)

**Comment by cornae** [comment]
Just checking ;)

> Op 23 okt. 2015 om 21:06 heeft Alexander Pilz notifications@github.com het volgende geschreven:
> 
> Argh, keep it in, me just too ignorant
> 
> Alexander Pilz (mobil)
>
